### ISSUE TITLE
Statoil incomplete data

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resource-projects-dataload#14]
Lets check once data is reloaded that payment type data is filled here:
Payment Type is not showing up in the payments section of project pages: http://alpha.resourceprojects.org/project/dz/insa-cjvofh.html

**Comment by caprenter** [comment]
I think this commit fixes this issue:
https://github.com/NRGI/resourceprojects.org-frontend/commit/9ca2c3373e2f145cb39735cbaba145147ef823f2

but check in the coming days
