### ISSUE TITLE
Jubilee appearing three times as project

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resource-projects-dataload#16]
Due to it being loaded from three different files.
Need to go back to source to add project ID where second appearance?
http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/country/GH.html

**Comment by timgdavies** [comment]
Correct. 

Ideally we might do this over the weekend hack - as we'll then have alpha.resourceprojects.org deployed and can use (and refine) the reconciliation process. 

Alternatively - we can do this manually before then...

**Comment by davidmihalyi** [comment]
Fine for this to be solved in Mexico, when we go back to spreadsheets.
