### ISSUE TITLE
Cote D'ivoire behaving strange due to spelling?

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resource-projects-dataload#17]
Or data load problem?

**Comment by caprenter** [comment]
Looks as though it is coming through this way in the data:
http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/default-view/http/resourceprojects.org/country/CI

**Comment by caprenter** [comment]
This is also reported here:
https://github.com/NRGI/resourceprojects.org-frontend/issues/185
