### ISSUE TITLE
Company count is not working

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resource-projects-dataload#20]
Company count (of companies involved in a project) is not working:
http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/country/ID.html
if can`t be fixed, better to hide.

**Comment by caprenter** [comment]
This also has the dual commodityType problem as reported here:
https://github.com/NRGI/resource-projects-dataload/issues/19

**Comment by caprenter** [comment]
I believe this is now fixed
