### ISSUE TITLE
Update template to include country code in 10. Payments & Receipts

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resource-projects-dataload#23]
Data shows only Ireland.
Probably lookup of country ID gets double hit?
http://alpha.resourceprojects.org/project/IE/fe31-jcvrob.html

**Comment by timgdavies** [comment]
I've tracked the source of this down to the lack of a Country ID column in tab 10. Payments and Receipts. 

The library which converts country names to country codes appears to be reading 'United Kingdom of Great Britain and Northern Ireland' as 'Ireland' for some reason. 

I will update the template to add this column, which should avoid this in future.
