### ISSUE TITLE
Intermittent bug: Companies showing as duplicate

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resource-projects-dataload#25]
http://alpha.resourceprojects.org/country/SL.html

**Comment by timgdavies** [comment]
I don't see any duplicates here. Please check.

**Comment by davidmihalyi** [comment]
Seems fixed now, used to show same single company multiple times.

**Comment by timgdavies** [comment]
Hmm. Nothing has changed since the comment - but glad it's not an outstanding issue.

**Comment by davidmihalyi** [comment]
duplicate is back??

**Comment by davidmihalyi** [comment]
it was gone earlier, and I just saw it again, very strange. maybe something cached?

**Comment by davidmihalyi** [comment]
![image](https://cloud.githubusercontent.com/assets/13120783/11181596/4c4ff7a2-8c5b-11e5-97cc-9880b4c5a687.png)

**Comment by timgdavies** [comment]
Ok. Now that is odd. I'll look into it.

**Comment by davidmihalyi** [comment]
do you see the duplicate too or is it just me?

**Comment by timgdavies** [comment]
I'm seeing it now as well.

**Comment by timgdavies** [comment]
Have you been loading any related data since it appeared?

**Comment by davidmihalyi** [comment]
Not at all

**Comment by timgdavies** [comment]
@Bjwebb @caprenter Flagging this one for your attention. 

Both @davidmihalyi and I _seem to_ have experienced an intermittent bug, whereby at one moment we're seeing duplicates, and then later we're not, and vice-versa.

I had a look, but until merges complete, wasn't sure which query to try and debug. 

Not sure what could be causing Virtuoso to provided different outputs for the DISTINCT statement each time - but we should look into this, and potentially have a test to ensure results from a page are consistent over time between changes - in case there is something deeper going on here. 

From the queries I have seen, it could be something to do with residual sameAs filters, which could removed.

**Comment by caprenter** [comment]
I also see some duplicates on: http://alpha.resourceprojects.org/country/AO.html (Somoil)

Writing a test to catch these should be easy enough - but on first inspection of the query I can't see anything.

One thing that struck me as odd is that in the Triples view - some companies (not all) can be found via 'hasLocation' directly, but the query used goes via projects first.

**Comment by timgdavies** [comment]
We should always go via the project.

A company may have a location of a country when it has been indicated as registered in that company. 

But that is not the same as doing business in a country, which would be via project.
