### ISSUE TITLE
Duplicate commodity

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resource-projects-dataload#27]
Seems to allow lower case inputs, but then displays them as seperate commodity.
http://alpha.resourceprojects.org/commodity

**Comment by timgdavies** [comment]
Fixed in the input sheet at https://docs.google.com/spreadsheets/d/1KDhQpIXLcy4uI8FJ17W9r7NPQIiQBdzjSzSCX7K9L7w/edit#gid=141760938
