### ISSUE TITLE
Company: Kosmos

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resource-projects-dataload#7]
From @davidmihalyi in [frontend repo](https://github.com/NRGI/resourceprojects.org-frontend/issues/53).

This would need to be scraped, but only 10 projects in this: 3 in Ghana, 4 in Ireland, 3 in Mauritania.
http://www.kosmosenergy.com/responsibility/transparency.php

**Comment by davidmihalyi** [comment]
I think this can be closed
